version: "4.0"

networks:
  apisix-desarrollo_facultad_yvaga_network:
    external: true

services:
  universidad-back:
    build: ../UniversidadBack
    container_name: universidad-back
    ports:
      - "3000:3000"
    networks:
      - apisix-desarrollo_facultad_yvaga_network

  universidad-front:
    build: .
    container_name: universidad-front
    ports:
      - "5173:80"
    depends_on:
      - universidad-back
    networks:
      - apisix-desarrollo_facultad_yvaga_network

  proctor-guard:
    build: ../ProctorGuard
    container_name: proctor-guard
    ports:
      - "5174:80"
    depends_on:
      - universidad-back
    networks:
      - apisix-desarrollo_facultad_yvaga_network

  apifaceid:
    build: ../SecurityPythonAPI
    container_name: apifaceid
    ports:
      - "8000:8000"
    depends_on:
      - universidad-back
      - universidad-front
    networks:
      - apisix-desarrollo_facultad_yvaga_network
