version: "4.0"

networks:
  apisix-desarrollo_facultad_yvaga_network:
    external: true

services:
  universidad-back:
    build: ../UniversidadBack
    container_name: universidad-back
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://ProjectFaceId_owner:F1VU3tiPOwHe@ep-purple-tree-a52xzu97.us-east-2.aws.neon.tech/ProjectFaceId?sslmode=require
      - JWT_PRIVATE_KEY=cbd372e00d9ea767fe60dfa86c08443a7d63896e5549b215d179fc9f5e8d25a5
      - SALT=10
    env_file:
      - ../UniversidadBack/.env
    networks:
      - apisix-desarrollo_facultad_yvaga_network

  universidad-front:
    build: .
    container_name: universidad-front
    ports:
      - "5173:80"
    depends_on:
      - universidad-back
    environment:
      - VITE_API_URL=http://161.35.53.140:3000/api
      - VITE_API_APP_URL=http://161.35.53.140:3010
      - VITE_API_PYTHON_URL=http://161.35.53.140:8000
    env_file:
      - ./.env
    networks:
      - apisix-desarrollo_facultad_yvaga_network

  proctor-guard:
    build: ../ProctorGuard
    container_name: proctor-guard
    ports:
      - "5174:80"
    depends_on:
      - universidad-back
    environment:
      - VITE_API_URL=http://161.35.53.140:3000/api
    env_file:
      - ../ProctorGuard/.env
    networks:
      - apisix-desarrollo_facultad_yvaga_network

  apifaceid:
    build: ../SecurityPythonAPI
    container_name: apifaceid
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://ProjectFaceId_owner:F1VU3tiPOwHe@ep-purple-tree-a52xzu97.us-east-2.aws.neon.tech/ProjectFaceId?sslmode=require
      - JWT_KEY=cbd372e00d9ea767fe60dfa86c08443a7d63896e5549b215d179fc9f5e8d25a5
    env_file:
      - ../SecurityPythonAPI/.env
    depends_on:
      - universidad-back
      - universidad-front
    networks:
      - apisix-desarrollo_facultad_yvaga_network
